### ISSUE TITLE
Theobroma Stairs

### ISSUE THREAD

**Issue by A5ho9999** [ACgamerReal/The-Chocolate-Mod-Expanded-Sources#2]
Theobroma Stairs aren't setup correct, they don't have a mineable tool and have no drop. I didn't check if other items have this issue

Fabric 1.20.1
Version: https://modrinth.com/mod/the-chocolate-mod/version/4.1

**Comment by ACgamerReal** [comment]
will be rolling out a fix to all of the problems today (hopefully) Thanks for submitting the problem otherwise I wouldn't have noticed probably

**Comment by A5ho9999** [comment]
Thanks, will let you know in a couple day when I update it
