### ISSUE TITLE
Zombie Chocolatier

### ISSUE THREAD

**Issue by winderine** [ACgamerReal/The-Chocolate-Mod-Expanded-Sources#3]
Missing texture for zombie chocolatier. Easy fix to just duplicate the villager folder and name it zombie_villager so I've made a resource pack doing that for myself.

**Comment by winderine** [comment]
resource pack

[ChocoZombie.zip](https://github.com/ACgamerReal/The-Chocolate-Mod-Expanded-Sources/files/13406785/ChocoZombie.zip)

**Comment by ACgamerReal** [comment]
Thanks for making the resource pack! Will be rolling out a fix soon!

**Comment by ACgamerReal** [comment]
Alright a fix will be rolling out next patch, thanks for submitting the issue!
